# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'attendance.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: rgb(29, 195, 255);\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(10, 10, 751, 571))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.username = QtWidgets.QLineEdit(self.page)
        self.username.setGeometry(QtCore.QRect(200, 120, 161, 21))
        self.username.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.username.setText("")
        self.username.setReadOnly(False)
        self.username.setObjectName("username")
        self.password_2 = QtWidgets.QLineEdit(self.page)
        self.password_2.setGeometry(QtCore.QRect(200, 170, 161, 20))
        self.password_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_2.setObjectName("password_2")
        self.login = QtWidgets.QPushButton(self.page)
        self.login.setGeometry(QtCore.QRect(120, 230, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.login.setFont(font)
        self.login.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.login.setObjectName("login")
        self.register_2 = QtWidgets.QPushButton(self.page)
        self.register_2.setGeometry(QtCore.QRect(340, 230, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.register_2.setFont(font)
        self.register_2.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.register_2.setObjectName("register_2")
        self.fpass = QtWidgets.QPushButton(self.page)
        self.fpass.setGeometry(QtCore.QRect(214, 230, 101, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fpass.setFont(font)
        self.fpass.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.fpass.setObjectName("fpass")
        self.label_9 = QtWidgets.QLabel(self.page)
        self.label_9.setGeometry(QtCore.QRect(140, 20, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Tekton Pro Cond")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.stackedWidget.addWidget(self.page)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.fusername = QtWidgets.QLineEdit(self.page_6)
        self.fusername.setGeometry(QtCore.QRect(210, 80, 191, 20))
        self.fusername.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fusername.setInputMask("")
        self.fusername.setObjectName("fusername")
        self.fsubmit = QtWidgets.QPushButton(self.page_6)
        self.fsubmit.setGeometry(QtCore.QRect(320, 140, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fsubmit.setFont(font)
        self.fsubmit.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.fsubmit.setObjectName("fsubmit")
        self.forback = QtWidgets.QPushButton(self.page_6)
        self.forback.setGeometry(QtCore.QRect(190, 140, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.forback.setFont(font)
        self.forback.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.forback.setObjectName("forback")
        self.stackedWidget.addWidget(self.page_6)
        self.page_8 = QtWidgets.QWidget()
        self.page_8.setObjectName("page_8")
        self.otp = QtWidgets.QLineEdit(self.page_8)
        self.otp.setGeometry(QtCore.QRect(220, 100, 151, 20))
        self.otp.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.otp.setObjectName("otp")
        self.otpsubmit = QtWidgets.QPushButton(self.page_8)
        self.otpsubmit.setGeometry(QtCore.QRect(250, 160, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.otpsubmit.setFont(font)
        self.otpsubmit.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.otpsubmit.setObjectName("otpsubmit")
        self.unamedis = QtWidgets.QLineEdit(self.page_8)
        self.unamedis.setGeometry(QtCore.QRect(220, 50, 141, 20))
        self.unamedis.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.unamedis.setObjectName("unamedis")
        self.stackedWidget.addWidget(self.page_8)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.newpass = QtWidgets.QLineEdit(self.page_7)
        self.newpass.setGeometry(QtCore.QRect(200, 120, 231, 20))
        self.newpass.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.newpass.setEchoMode(QtWidgets.QLineEdit.Password)
        self.newpass.setObjectName("newpass")
        self.newpasssubmit = QtWidgets.QPushButton(self.page_7)
        self.newpasssubmit.setGeometry(QtCore.QRect(220, 180, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.newpasssubmit.setFont(font)
        self.newpasssubmit.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.newpasssubmit.setObjectName("newpasssubmit")
        self.newpassuser = QtWidgets.QLineEdit(self.page_7)
        self.newpassuser.setGeometry(QtCore.QRect(190, 70, 241, 20))
        self.newpassuser.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.newpassuser.setObjectName("newpassuser")
        self.stackedWidget.addWidget(self.page_7)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.name = QtWidgets.QLineEdit(self.page_2)
        self.name.setGeometry(QtCore.QRect(90, 90, 113, 20))
        self.name.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.name.setObjectName("name")
        self.dept = QtWidgets.QLineEdit(self.page_2)
        self.dept.setGeometry(QtCore.QRect(90, 140, 113, 20))
        self.dept.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.dept.setObjectName("dept")
        self.password = QtWidgets.QLineEdit(self.page_2)
        self.password.setGeometry(QtCore.QRect(360, 110, 131, 20))
        self.password.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password.setObjectName("password")
        self.email = QtWidgets.QLineEdit(self.page_2)
        self.email.setGeometry(QtCore.QRect(360, 160, 141, 20))
        self.email.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.email.setObjectName("email")
        self.sem = QtWidgets.QLineEdit(self.page_2)
        self.sem.setGeometry(QtCore.QRect(90, 190, 113, 20))
        self.sem.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sem.setObjectName("sem")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(20, 90, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setGeometry(QtCore.QRect(280, 110, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setGeometry(QtCore.QRect(20, 140, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setGeometry(QtCore.QRect(300, 160, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.page_2)
        self.label_6.setGeometry(QtCore.QRect(276, 210, 61, 20))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.mobileno = QtWidgets.QLineEdit(self.page_2)
        self.mobileno.setGeometry(QtCore.QRect(360, 210, 141, 20))
        self.mobileno.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.mobileno.setObjectName("mobileno")
        self.submit = QtWidgets.QPushButton(self.page_2)
        self.submit.setGeometry(QtCore.QRect(320, 300, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.submit.setFont(font)
        self.submit.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.submit.setObjectName("submit")
        self.back = QtWidgets.QPushButton(self.page_2)
        self.back.setGeometry(QtCore.QRect(90, 300, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.back.setFont(font)
        self.back.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.back.setObjectName("back")
        self.label_7 = QtWidgets.QLabel(self.page_2)
        self.label_7.setGeometry(QtCore.QRect(10, 240, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.username_3 = QtWidgets.QLineEdit(self.page_2)
        self.username_3.setGeometry(QtCore.QRect(90, 240, 113, 20))
        self.username_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.username_3.setObjectName("username_3")
        self.label_10 = QtWidgets.QLabel(self.page_2)
        self.label_10.setGeometry(QtCore.QRect(200, 20, 331, 41))
        font = QtGui.QFont()
        font.setFamily("Tekton Pro")
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.page_2)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.enteratt = QtWidgets.QPushButton(self.page_4)
        self.enteratt.setGeometry(QtCore.QRect(260, 120, 131, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.enteratt.setFont(font)
        self.enteratt.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.enteratt.setObjectName("enteratt")
        self.viewatt = QtWidgets.QPushButton(self.page_4)
        self.viewatt.setGeometry(QtCore.QRect(260, 210, 131, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.viewatt.setFont(font)
        self.viewatt.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.viewatt.setObjectName("viewatt")
        self.backlogin = QtWidgets.QPushButton(self.page_4)
        self.backlogin.setGeometry(QtCore.QRect(260, 370, 131, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.backlogin.setFont(font)
        self.backlogin.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.backlogin.setObjectName("backlogin")
        self.un = QtWidgets.QLabel(self.page_4)
        self.un.setGeometry(QtCore.QRect(80, 80, 121, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.un.setFont(font)
        self.un.setObjectName("un")
        self.dept_2 = QtWidgets.QLabel(self.page_4)
        self.dept_2.setGeometry(QtCore.QRect(440, 80, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.dept_2.setFont(font)
        self.dept_2.setObjectName("dept_2")
        self.calculate = QtWidgets.QPushButton(self.page_4)
        self.calculate.setGeometry(QtCore.QRect(260, 290, 131, 51))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.calculate.setFont(font)
        self.calculate.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.calculate.setObjectName("calculate")
        self.stackedWidget.addWidget(self.page_4)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.calendar = QtWidgets.QCalendarWidget(self.page_3)
        self.calendar.setGeometry(QtCore.QRect(20, 40, 312, 183))
        self.calendar.setStyleSheet("")
        self.calendar.setObjectName("calendar")
        self.attsubmit = QtWidgets.QPushButton(self.page_3)
        self.attsubmit.setGeometry(QtCore.QRect(340, 270, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.attsubmit.setFont(font)
        self.attsubmit.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.attsubmit.setObjectName("attsubmit")
        self.attback = QtWidgets.QPushButton(self.page_3)
        self.attback.setGeometry(QtCore.QRect(160, 270, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.attback.setFont(font)
        self.attback.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.attback.setObjectName("attback")
        self.sub1 = QtWidgets.QLineEdit(self.page_3)
        self.sub1.setGeometry(QtCore.QRect(410, 60, 61, 21))
        self.sub1.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub1.setObjectName("sub1")
        self.sub2 = QtWidgets.QLineEdit(self.page_3)
        self.sub2.setGeometry(QtCore.QRect(610, 60, 61, 21))
        self.sub2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub2.setObjectName("sub2")
        self.sub3 = QtWidgets.QLineEdit(self.page_3)
        self.sub3.setGeometry(QtCore.QRect(410, 100, 61, 20))
        self.sub3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub3.setObjectName("sub3")
        self.sub4 = QtWidgets.QLineEdit(self.page_3)
        self.sub4.setGeometry(QtCore.QRect(610, 100, 61, 20))
        self.sub4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub4.setObjectName("sub4")
        self.sub5 = QtWidgets.QLineEdit(self.page_3)
        self.sub5.setGeometry(QtCore.QRect(410, 140, 61, 20))
        self.sub5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub5.setObjectName("sub5")
        self.sub6 = QtWidgets.QLineEdit(self.page_3)
        self.sub6.setGeometry(QtCore.QRect(610, 130, 61, 20))
        self.sub6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub6.setObjectName("sub6")
        self.label_8 = QtWidgets.QLabel(self.page_3)
        self.label_8.setGeometry(QtCore.QRect(430, 10, 201, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.sub1l = QtWidgets.QLabel(self.page_3)
        self.sub1l.setGeometry(QtCore.QRect(350, 60, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sub1l.setFont(font)
        self.sub1l.setObjectName("sub1l")
        self.sub2l = QtWidgets.QLabel(self.page_3)
        self.sub2l.setGeometry(QtCore.QRect(550, 60, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sub2l.setFont(font)
        self.sub2l.setObjectName("sub2l")
        self.sub3l = QtWidgets.QLabel(self.page_3)
        self.sub3l.setGeometry(QtCore.QRect(350, 100, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sub3l.setFont(font)
        self.sub3l.setObjectName("sub3l")
        self.sub4l = QtWidgets.QLabel(self.page_3)
        self.sub4l.setGeometry(QtCore.QRect(550, 100, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sub4l.setFont(font)
        self.sub4l.setObjectName("sub4l")
        self.sub5l = QtWidgets.QLabel(self.page_3)
        self.sub5l.setGeometry(QtCore.QRect(350, 140, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sub5l.setFont(font)
        self.sub5l.setObjectName("sub5l")
        self.sub6l = QtWidgets.QLabel(self.page_3)
        self.sub6l.setGeometry(QtCore.QRect(550, 140, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sub6l.setFont(font)
        self.sub6l.setObjectName("sub6l")
        self.update = QtWidgets.QPushButton(self.page_3)
        self.update.setGeometry(QtCore.QRect(490, 270, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.update.setFont(font)
        self.update.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.update.setObjectName("update")
        self.user = QtWidgets.QLabel(self.page_3)
        self.user.setGeometry(QtCore.QRect(240, 10, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.user.setFont(font)
        self.user.setObjectName("user")
        self.sub1lec = QtWidgets.QLineEdit(self.page_3)
        self.sub1lec.setGeometry(QtCore.QRect(480, 60, 61, 20))
        self.sub1lec.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub1lec.setObjectName("sub1lec")
        self.sub2lec = QtWidgets.QLineEdit(self.page_3)
        self.sub2lec.setGeometry(QtCore.QRect(680, 60, 61, 20))
        self.sub2lec.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub2lec.setObjectName("sub2lec")
        self.sub6lec = QtWidgets.QLineEdit(self.page_3)
        self.sub6lec.setGeometry(QtCore.QRect(680, 130, 61, 20))
        self.sub6lec.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub6lec.setObjectName("sub6lec")
        self.sub4lec = QtWidgets.QLineEdit(self.page_3)
        self.sub4lec.setGeometry(QtCore.QRect(680, 100, 61, 20))
        self.sub4lec.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub4lec.setObjectName("sub4lec")
        self.sub5lec = QtWidgets.QLineEdit(self.page_3)
        self.sub5lec.setGeometry(QtCore.QRect(480, 140, 51, 20))
        self.sub5lec.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub5lec.setObjectName("sub5lec")
        self.sub3lec = QtWidgets.QLineEdit(self.page_3)
        self.sub3lec.setGeometry(QtCore.QRect(480, 100, 61, 20))
        self.sub3lec.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub3lec.setObjectName("sub3lec")
        self.label_14 = QtWidgets.QLabel(self.page_3)
        self.label_14.setGeometry(QtCore.QRect(410, 30, 61, 20))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.page_3)
        self.label_15.setGeometry(QtCore.QRect(480, 30, 47, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.page_3)
        self.label_16.setGeometry(QtCore.QRect(600, 30, 61, 16))
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.page_3)
        self.label_17.setGeometry(QtCore.QRect(680, 30, 47, 13))
        self.label_17.setObjectName("label_17")
        self.stackedWidget.addWidget(self.page_3)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.table = QtWidgets.QTableWidget(self.page_5)
        self.table.setGeometry(QtCore.QRect(25, 111, 681, 341))
        self.table.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.table.setRowCount(30)
        self.table.setColumnCount(10)
        self.table.setObjectName("table")
        self.viewback = QtWidgets.QPushButton(self.page_5)
        self.viewback.setGeometry(QtCore.QRect(60, 480, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.viewback.setFont(font)
        self.viewback.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.viewback.setObjectName("viewback")
        self.file = QtWidgets.QPushButton(self.page_5)
        self.file.setGeometry(QtCore.QRect(250, 480, 91, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.file.setFont(font)
        self.file.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.file.setObjectName("file")
        self.analysis = QtWidgets.QPushButton(self.page_5)
        self.analysis.setGeometry(QtCore.QRect(440, 480, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.analysis.setFont(font)
        self.analysis.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.analysis.setObjectName("analysis")
        self.usernameview = QtWidgets.QLabel(self.page_5)
        self.usernameview.setGeometry(QtCore.QRect(30, 50, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.usernameview.setFont(font)
        self.usernameview.setObjectName("usernameview")
        self.stackedWidget.addWidget(self.page_5)
        self.page_9 = QtWidgets.QWidget()
        self.page_9.setObjectName("page_9")
        self.sub1name = QtWidgets.QLineEdit(self.page_9)
        self.sub1name.setGeometry(QtCore.QRect(60, 90, 113, 20))
        self.sub1name.setObjectName("sub1name")
        self.sub1att = QtWidgets.QLineEdit(self.page_9)
        self.sub1att.setGeometry(QtCore.QRect(200, 90, 113, 20))
        self.sub1att.setObjectName("sub1att")
        self.sub2name = QtWidgets.QLineEdit(self.page_9)
        self.sub2name.setGeometry(QtCore.QRect(60, 140, 113, 20))
        self.sub2name.setObjectName("sub2name")
        self.sub2att = QtWidgets.QLineEdit(self.page_9)
        self.sub2att.setGeometry(QtCore.QRect(200, 140, 113, 20))
        self.sub2att.setObjectName("sub2att")
        self.sub3name = QtWidgets.QLineEdit(self.page_9)
        self.sub3name.setGeometry(QtCore.QRect(60, 180, 113, 20))
        self.sub3name.setObjectName("sub3name")
        self.sub3att = QtWidgets.QLineEdit(self.page_9)
        self.sub3att.setGeometry(QtCore.QRect(200, 180, 113, 20))
        self.sub3att.setObjectName("sub3att")
        self.sub4name = QtWidgets.QLineEdit(self.page_9)
        self.sub4name.setGeometry(QtCore.QRect(60, 230, 113, 20))
        self.sub4name.setObjectName("sub4name")
        self.sub4att = QtWidgets.QLineEdit(self.page_9)
        self.sub4att.setGeometry(QtCore.QRect(200, 230, 113, 20))
        self.sub4att.setObjectName("sub4att")
        self.sub5name = QtWidgets.QLineEdit(self.page_9)
        self.sub5name.setGeometry(QtCore.QRect(60, 270, 113, 20))
        self.sub5name.setObjectName("sub5name")
        self.sub5att = QtWidgets.QLineEdit(self.page_9)
        self.sub5att.setGeometry(QtCore.QRect(200, 270, 113, 20))
        self.sub5att.setObjectName("sub5att")
        self.sub6name = QtWidgets.QLineEdit(self.page_9)
        self.sub6name.setGeometry(QtCore.QRect(60, 310, 113, 20))
        self.sub6name.setObjectName("sub6name")
        self.sub6att = QtWidgets.QLineEdit(self.page_9)
        self.sub6att.setGeometry(QtCore.QRect(200, 310, 113, 20))
        self.sub6att.setObjectName("sub6att")
        self.monthno = QtWidgets.QLineEdit(self.page_9)
        self.monthno.setGeometry(QtCore.QRect(60, 30, 113, 20))
        self.monthno.setObjectName("monthno")
        self.sub1total = QtWidgets.QLineEdit(self.page_9)
        self.sub1total.setGeometry(QtCore.QRect(360, 90, 113, 20))
        self.sub1total.setObjectName("sub1total")
        self.sub1attper = QtWidgets.QLineEdit(self.page_9)
        self.sub1attper.setGeometry(QtCore.QRect(500, 90, 113, 20))
        self.sub1attper.setObjectName("sub1attper")
        self.sub2total = QtWidgets.QLineEdit(self.page_9)
        self.sub2total.setGeometry(QtCore.QRect(360, 140, 113, 20))
        self.sub2total.setObjectName("sub2total")
        self.sub2attper = QtWidgets.QLineEdit(self.page_9)
        self.sub2attper.setGeometry(QtCore.QRect(500, 140, 113, 20))
        self.sub2attper.setObjectName("sub2attper")
        self.sub3total = QtWidgets.QLineEdit(self.page_9)
        self.sub3total.setGeometry(QtCore.QRect(360, 180, 113, 20))
        self.sub3total.setObjectName("sub3total")
        self.sub3attper = QtWidgets.QLineEdit(self.page_9)
        self.sub3attper.setGeometry(QtCore.QRect(500, 180, 113, 20))
        self.sub3attper.setObjectName("sub3attper")
        self.sub4total = QtWidgets.QLineEdit(self.page_9)
        self.sub4total.setGeometry(QtCore.QRect(360, 230, 113, 20))
        self.sub4total.setObjectName("sub4total")
        self.sub4attper = QtWidgets.QLineEdit(self.page_9)
        self.sub4attper.setGeometry(QtCore.QRect(500, 230, 113, 20))
        self.sub4attper.setObjectName("sub4attper")
        self.sub5total = QtWidgets.QLineEdit(self.page_9)
        self.sub5total.setGeometry(QtCore.QRect(360, 270, 113, 20))
        self.sub5total.setObjectName("sub5total")
        self.sub5attper = QtWidgets.QLineEdit(self.page_9)
        self.sub5attper.setGeometry(QtCore.QRect(500, 270, 113, 20))
        self.sub5attper.setObjectName("sub5attper")
        self.sub6total = QtWidgets.QLineEdit(self.page_9)
        self.sub6total.setGeometry(QtCore.QRect(360, 310, 113, 20))
        self.sub6total.setObjectName("sub6total")
        self.sub6attper = QtWidgets.QLineEdit(self.page_9)
        self.sub6attper.setGeometry(QtCore.QRect(510, 320, 113, 20))
        self.sub6attper.setObjectName("sub6attper")
        self.lineEdit = QtWidgets.QLineEdit(self.page_9)
        self.lineEdit.setGeometry(QtCore.QRect(210, 30, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.backattcal = QtWidgets.QPushButton(self.page_9)
        self.backattcal.setGeometry(QtCore.QRect(160, 380, 75, 23))
        self.backattcal.setObjectName("backattcal")
        self.stackedWidget.addWidget(self.page_9)
        self.page_10 = QtWidgets.QWidget()
        self.page_10.setObjectName("page_10")
        self.caluser = QtWidgets.QLabel(self.page_10)
        self.caluser.setGeometry(QtCore.QRect(30, 40, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.caluser.setFont(font)
        self.caluser.setObjectName("caluser")
        self.label_11 = QtWidgets.QLabel(self.page_10)
        self.label_11.setGeometry(QtCore.QRect(250, 10, 331, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.cal2 = QtWidgets.QCalendarWidget(self.page_10)
        self.cal2.setGeometry(QtCore.QRect(370, 110, 312, 183))
        self.cal2.setObjectName("cal2")
        self.label_12 = QtWidgets.QLabel(self.page_10)
        self.label_12.setGeometry(QtCore.QRect(90, 90, 47, 13))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.page_10)
        self.label_13.setGeometry(QtCore.QRect(440, 80, 47, 13))
        self.label_13.setObjectName("label_13")
        self.calsubmit = QtWidgets.QPushButton(self.page_10)
        self.calsubmit.setGeometry(QtCore.QRect(280, 380, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.calsubmit.setFont(font)
        self.calsubmit.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.calsubmit.setObjectName("calsubmit")
        self.cal1 = QtWidgets.QCalendarWidget(self.page_10)
        self.cal1.setGeometry(QtCore.QRect(30, 110, 312, 183))
        self.cal1.setStyleSheet("")
        self.cal1.setObjectName("cal1")
        self.backcal = QtWidgets.QPushButton(self.page_10)
        self.backcal.setGeometry(QtCore.QRect(430, 380, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.backcal.setFont(font)
        self.backcal.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.backcal.setObjectName("backcal")
        self.deptcal = QtWidgets.QLabel(self.page_10)
        self.deptcal.setGeometry(QtCore.QRect(180, 40, 47, 13))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.deptcal.setFont(font)
        self.deptcal.setObjectName("deptcal")
        self.stackedWidget.addWidget(self.page_10)
        self.page_11 = QtWidgets.QWidget()
        self.page_11.setObjectName("page_11")
        self.attshowname = QtWidgets.QLabel(self.page_11)
        self.attshowname.setGeometry(QtCore.QRect(30, 20, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.attshowname.setFont(font)
        self.attshowname.setObjectName("attshowname")
        self.sub1s = QtWidgets.QLabel(self.page_11)
        self.sub1s.setGeometry(QtCore.QRect(40, 100, 47, 13))
        self.sub1s.setObjectName("sub1s")
        self.sub3s = QtWidgets.QLabel(self.page_11)
        self.sub3s.setGeometry(QtCore.QRect(40, 150, 47, 13))
        self.sub3s.setObjectName("sub3s")
        self.sub5s = QtWidgets.QLabel(self.page_11)
        self.sub5s.setGeometry(QtCore.QRect(40, 200, 47, 13))
        self.sub5s.setObjectName("sub5s")
        self.sub2s = QtWidgets.QLabel(self.page_11)
        self.sub2s.setGeometry(QtCore.QRect(300, 100, 47, 13))
        self.sub2s.setObjectName("sub2s")
        self.sub4s = QtWidgets.QLabel(self.page_11)
        self.sub4s.setGeometry(QtCore.QRect(300, 160, 47, 13))
        self.sub4s.setObjectName("sub4s")
        self.sub6s = QtWidgets.QLabel(self.page_11)
        self.sub6s.setGeometry(QtCore.QRect(300, 210, 47, 13))
        self.sub6s.setObjectName("sub6s")
        self.sub6sh = QtWidgets.QLineEdit(self.page_11)
        self.sub6sh.setGeometry(QtCore.QRect(370, 200, 113, 20))
        self.sub6sh.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub6sh.setObjectName("sub6sh")
        self.sub2sh = QtWidgets.QLineEdit(self.page_11)
        self.sub2sh.setGeometry(QtCore.QRect(370, 100, 113, 20))
        self.sub2sh.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub2sh.setObjectName("sub2sh")
        self.sub4sh = QtWidgets.QLineEdit(self.page_11)
        self.sub4sh.setGeometry(QtCore.QRect(370, 150, 113, 20))
        self.sub4sh.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub4sh.setObjectName("sub4sh")
        self.sub3sh = QtWidgets.QLineEdit(self.page_11)
        self.sub3sh.setGeometry(QtCore.QRect(120, 150, 113, 20))
        self.sub3sh.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"\n"
"")
        self.sub3sh.setObjectName("sub3sh")
        self.sub1sh = QtWidgets.QLineEdit(self.page_11)
        self.sub1sh.setGeometry(QtCore.QRect(120, 100, 113, 20))
        self.sub1sh.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.sub1sh.setObjectName("sub1sh")
        self.sub5sh = QtWidgets.QLineEdit(self.page_11)
        self.sub5sh.setGeometry(QtCore.QRect(120, 200, 113, 20))
        self.sub5sh.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.sub5sh.setObjectName("sub5sh")
        self.attcalsh = QtWidgets.QLineEdit(self.page_11)
        self.attcalsh.setGeometry(QtCore.QRect(230, 300, 131, 51))
        self.attcalsh.setObjectName("attcalsh")
        self.label_24 = QtWidgets.QLabel(self.page_11)
        self.label_24.setGeometry(QtCore.QRect(110, 300, 81, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.attshowdept = QtWidgets.QLabel(self.page_11)
        self.attshowdept.setGeometry(QtCore.QRect(220, 20, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.attshowdept.setFont(font)
        self.attshowdept.setObjectName("attshowdept")
        self.fromd = QtWidgets.QLabel(self.page_11)
        self.fromd.setGeometry(QtCore.QRect(40, 50, 151, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.fromd.setFont(font)
        self.fromd.setObjectName("fromd")
        self.backcalshow = QtWidgets.QPushButton(self.page_11)
        self.backcalshow.setGeometry(QtCore.QRect(170, 400, 75, 23))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.backcalshow.setFont(font)
        self.backcalshow.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.backcalshow.setObjectName("backcalshow")
        self.tod = QtWidgets.QLabel(self.page_11)
        self.tod.setGeometry(QtCore.QRect(290, 50, 251, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tod.setFont(font)
        self.tod.setObjectName("tod")
        self.label_18 = QtWidgets.QLabel(self.page_11)
        self.label_18.setGeometry(QtCore.QRect(220, 50, 47, 13))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.stackedWidget.addWidget(self.page_11)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.username.setPlaceholderText(_translate("MainWindow", "enter username"))
        self.password_2.setPlaceholderText(_translate("MainWindow", "enter password"))
        self.login.setText(_translate("MainWindow", "Login"))
        self.register_2.setText(_translate("MainWindow", "Register"))
        self.fpass.setText(_translate("MainWindow", "Forget Password"))
        self.label_9.setText(_translate("MainWindow", "Attendance Keeper"))
        self.fusername.setPlaceholderText(_translate("MainWindow", "enter username"))
        self.fsubmit.setText(_translate("MainWindow", "Submit"))
        self.forback.setText(_translate("MainWindow", "Back"))
        self.otp.setPlaceholderText(_translate("MainWindow", "enter otp"))
        self.otpsubmit.setText(_translate("MainWindow", "Submit"))
        self.newpass.setPlaceholderText(_translate("MainWindow", "enter new password"))
        self.newpasssubmit.setText(_translate("MainWindow", "Submit"))
        self.label.setText(_translate("MainWindow", "Name:"))
        self.label_2.setText(_translate("MainWindow", "Password:"))
        self.label_3.setText(_translate("MainWindow", "Dept:"))
        self.label_4.setText(_translate("MainWindow", "email:"))
        self.label_5.setText(_translate("MainWindow", "sem:"))
        self.label_6.setText(_translate("MainWindow", "Mobile no:"))
        self.submit.setText(_translate("MainWindow", "Submit"))
        self.back.setText(_translate("MainWindow", "Back"))
        self.label_7.setText(_translate("MainWindow", "username:"))
        self.label_10.setText(_translate("MainWindow", "Register"))
        self.enteratt.setText(_translate("MainWindow", "Enter Attendance"))
        self.viewatt.setText(_translate("MainWindow", "View Attendance"))
        self.backlogin.setText(_translate("MainWindow", "Back"))
        self.un.setText(_translate("MainWindow", "TextLabel"))
        self.dept_2.setText(_translate("MainWindow", "TextLabel"))
        self.calculate.setText(_translate("MainWindow", "Calculate"))
        self.attsubmit.setText(_translate("MainWindow", "Submit"))
        self.attback.setText(_translate("MainWindow", "Back"))
        self.sub1.setPlaceholderText(_translate("MainWindow", "sub1"))
        self.sub2.setPlaceholderText(_translate("MainWindow", "sub2"))
        self.sub3.setPlaceholderText(_translate("MainWindow", "sub3"))
        self.sub4.setPlaceholderText(_translate("MainWindow", "sub4"))
        self.sub5.setPlaceholderText(_translate("MainWindow", "sub5"))
        self.sub6.setPlaceholderText(_translate("MainWindow", "sub6"))
        self.label_8.setText(_translate("MainWindow", "Enter no of lecs attended"))
        self.sub1l.setText(_translate("MainWindow", "TextLabel"))
        self.sub2l.setText(_translate("MainWindow", "TextLabel"))
        self.sub3l.setText(_translate("MainWindow", "TextLabel"))
        self.sub4l.setText(_translate("MainWindow", "TextLabel"))
        self.sub5l.setText(_translate("MainWindow", "TextLabel"))
        self.sub6l.setText(_translate("MainWindow", "TextLabel"))
        self.update.setText(_translate("MainWindow", "update"))
        self.user.setText(_translate("MainWindow", "TextLabel"))
        self.sub1lec.setPlaceholderText(_translate("MainWindow", "sub1"))
        self.sub2lec.setPlaceholderText(_translate("MainWindow", "sub2"))
        self.sub6lec.setPlaceholderText(_translate("MainWindow", "sub6"))
        self.sub4lec.setPlaceholderText(_translate("MainWindow", "sub4"))
        self.sub5lec.setPlaceholderText(_translate("MainWindow", "sub5"))
        self.sub3lec.setPlaceholderText(_translate("MainWindow", "sub3"))
        self.label_14.setText(_translate("MainWindow", "Attended"))
        self.label_15.setText(_translate("MainWindow", "Total"))
        self.label_16.setText(_translate("MainWindow", "Attended"))
        self.label_17.setText(_translate("MainWindow", "Total"))
        self.viewback.setText(_translate("MainWindow", "Back"))
        self.file.setText(_translate("MainWindow", "Generate file"))
        self.analysis.setText(_translate("MainWindow", "Analysis"))
        self.usernameview.setText(_translate("MainWindow", "TextLabel"))
        self.monthno.setPlaceholderText(_translate("MainWindow", "enter month no"))
        self.backattcal.setText(_translate("MainWindow", "Back"))
        self.caluser.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "Enter Date to calculate Attendance"))
        self.label_12.setText(_translate("MainWindow", "From"))
        self.label_13.setText(_translate("MainWindow", "To"))
        self.calsubmit.setText(_translate("MainWindow", "Submit"))
        self.backcal.setText(_translate("MainWindow", "Back"))
        self.deptcal.setText(_translate("MainWindow", "TextLabel"))
        self.attshowname.setText(_translate("MainWindow", "TextLabel"))
        self.sub1s.setText(_translate("MainWindow", "TextLabel"))
        self.sub3s.setText(_translate("MainWindow", "TextLabel"))
        self.sub5s.setText(_translate("MainWindow", "TextLabel"))
        self.sub2s.setText(_translate("MainWindow", "TextLabel"))
        self.sub4s.setText(_translate("MainWindow", "TextLabel"))
        self.sub6s.setText(_translate("MainWindow", "TextLabel"))
        self.label_24.setText(_translate("MainWindow", "Attendance"))
        self.attshowdept.setText(_translate("MainWindow", "TextLabel"))
        self.fromd.setText(_translate("MainWindow", "TextLabel"))
        self.backcalshow.setText(_translate("MainWindow", "Back"))
        self.tod.setText(_translate("MainWindow", "TextLabel"))
        self.label_18.setText(_translate("MainWindow", "To"))

import xyz_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

